# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(0, 0, 801, 371))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("this_is_paradise.jpg"))
        self.pic.setScaledContents(True)
        self.pic.setAlignment(QtCore.Qt.AlignCenter)
        self.pic.setObjectName("pic")
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setGeometry(QtCore.QRect(660, 470, 141, 81))
        self.Save.setObjectName("Save")
        self.Open = QtWidgets.QPushButton(self.centralwidget)
        self.Open.setGeometry(QtCore.QRect(660, 380, 141, 81))
        self.Open.setObjectName("Open")
        self.x_slider = QtWidgets.QSlider(self.centralwidget)
        self.x_slider.setGeometry(QtCore.QRect(90, 410, 521, 21))
        self.x_slider.setMinimum(-100)
        self.x_slider.setMaximum(100)
        self.x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.x_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.x_slider.setTickInterval(10)
        self.x_slider.setObjectName("x_slider")
        self.x_crop = QtWidgets.QLabel(self.centralwidget)
        self.x_crop.setGeometry(QtCore.QRect(90, 380, 101, 16))
        self.x_crop.setObjectName("x_crop")
        self.y_slider = QtWidgets.QSlider(self.centralwidget)
        self.y_slider.setGeometry(QtCore.QRect(90, 490, 521, 21))
        self.y_slider.setMinimum(-100)
        self.y_slider.setMaximum(100)
        self.y_slider.setOrientation(QtCore.Qt.Horizontal)
        self.y_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.y_slider.setTickInterval(10)
        self.y_slider.setObjectName("y_slider")
        self.y_crop = QtWidgets.QLabel(self.centralwidget)
        self.y_crop.setGeometry(QtCore.QRect(90, 460, 101, 16))
        self.y_crop.setObjectName("y_crop")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.x_slider.valueChanged.connect(self.x_v_change)
        self.y_slider.valueChanged.connect(self.y_v_change)
        self.Open.clicked.connect(self.open_dialog_box)
        self.Save.clicked.connect(self.save_pic)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.Open.setText(_translate("MainWindow", "Open"))
        self.x_crop.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">X_crop</span></p></body></html>"))
        self.y_crop.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Y_crop</span></p><p><br/></p></body></html>"))


    def x_v_change(self):
        value = str(self.x_slider.value())
        print(f"x: {value}")

    def y_v_change(self):
        value = str(self.y_slider.value())
        print(f"y: {value}")

    def open_dialog_box(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        print(filename[0])

    def save_pic(self):
        print("pic saved")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
